### PR TITLE
[WIP] Add support for Python 3.5 and 3.6.

### PR DESCRIPTION
**Pull request by icemac**
There are currently two tests failing. It would be nice if someone could look into them as I do not use this package at all.

### CODE REVIEW

**Comment by icemac** [comment]
I investigated the failures an found that the index contains a key with the value `''` (aka empty string). It points to the `DummyContent` object. Something seems to be wrong during indexing it for the first time – when it does not yet have an `cmf_uid` attribute – turning the `AttributeError` into an empty string.

**Comment by icemac** [comment]
@dataflake Do you might know what's causing this behaviour?

**Comment by dataflake** [comment]
I'm afraid I don't have any knowledge here. Never used CMFUid.

**Comment by icemac** [comment]
@ale-rt Thank you for fixing this in #7.

**Pull request closed without merging**
